### Register
POST http://localhost:5680/api/v1/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "Bean123",
  "email": "bean123@karo.gay",
  "authenticationMethods": [
    {
      "type": "password",
      "details": {
        "password": "secretbean!"
      }
    }
  ]
}

### Login
POST http://localhost:5680/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "Bean123",
  "password": "secretbean!"
}

> {%
    client.global.set('bearer_token', response.headers.valueOf("authorization"));
%}

### Logout
POST http://localhost:5680/api/v1/auth/logout
Authorization: {{bearer_token}}

### make a public token
POST http://localhost:5680/api/v1/auth/publicToken
Content-Type: application/json
Accept: application/json
Authorization: {{bearer_token}}

{
  "publicKey": "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEARXSQpJzQ65Tub7lwMBZhaWjI2lVsZF+gtKnroGTg6OI=,\n-----END PUBLIC KEY-----"
}