### Create invite
POST localhost:5680/api/v1/servers/8c93a8fb-925d-48f3-802e-13af70fa534f/invites
Authorization: {{bearer_token}}
Accept: application/json
Content-Type: application/json

{

}

### Get all invites in a server
GET localhost:5680/api/v1/servers/86e8eab3-b293-413d-873b-764666af8415/invites
Authorization: {{bearer_token}}
Accept: application/json

### Join a server
POST localhost:5680/api/v1/servers/8c93a8fb-925d-48f3-802e-13af70fa534f/invites/79997001-8416-4fed-adc6-42f1fc379df7/join
Authorization: {{bearer_token}}
Accept: application/json
