### Create invite
POST localhost:5680/api/v1/servers/5662630e-7926-4c66-84a5-73d8488c8c15/channels/bf8b7755-c307-4fed-ab37-004d0278ae22/messages
Authorization: {{bearer_token}}
Accept: application/json
Content-Type: application/json

{
  "type": "text",
  "details": {
    "content": "Hello World!"
  }
}